[package]
name = "qemu_linux_process"
version = "0.16.0"
authors = ["Romain Malmain <rmalmain@pm.me>"]
edition = "2021"

[features]
default = ["lqemu"]

## Build and run the target with the Nyx API instead of the built-in LibAFL QEMU API.
nyx = []

## Build and run the target with the LibAFL QEMU API.
lqemu = []

shared = ["libafl_qemu/shared"]

[profile.release]
incremental = true
debug = true
lto = "fat"
codegen-units = 1

[dependencies]
rand = "0.8"
#libafl = { path = "../../../crates/libafl" }
#libafl_bolts = { path = "../../../crates/libafl_bolts" }
#ibafl_qemu = { path = "../../../crates/libafl_qemu", default-features = false, features = [
# "x86_64",
# "systemmode",
# # "paranoid_debug",
# ]}

libafl = { path = "/home/sarissa/tools/LibAFL/crates/libafl" }
libafl_bolts = { path = "/home/sarissa/tools/LibAFL/crates/libafl_bolts" }
libafl_qemu = { path = "/home/sarissa/tools/LibAFL/crates/libafl_qemu", default-features = false, features = [
  "x86_64",
  "systemmode",
  # "paranoid_debug",
] }
libafl_targets = { path = "/home/sarissa/tools/LibAFL/crates/libafl_targets" } 

env_logger = "0.11.5"
#ibafl_targets = { path = "../../../crates/libafl_targets" }
log = "0.4.22"

[build-dependencies]
libafl_qemu_build = { path = "/home/sarissa/tools/LibAFL/crates/libafl_qemu/libafl_qemu_build" }


#added
serde = { version = "1", features = ["derive"] }
serde_arrays = "0.1"
bincode = "1"